/**
 * Localized search terminology.
 *
 * Requirement: "Search terminology must automatically adapt to the local
 * language of the selected country." A query for `spa dealer` returns almost
 * nothing useful in Morocco, Poland or Japan — the local trade words do.
 *
 * Each category maps a language code to the words local businesses actually
 * use to describe themselves. English is always available as a fallback.
 */

export type TermCategory =
  | 'spa'
  | 'hotTub'
  | 'swimSpa'
  | 'pool'
  | 'poolBuilder'
  | 'poolInstaller'
  | 'wellness'
  | 'sauna'
  | 'hammam'
  | 'outdoorLiving'
  | 'gardenPremium'
  | 'hotelWellness';

type TermMap = Record<string, string[]>;

/**
 * NOTE ON `spa`: in most Romance languages the bare word "spa" also means a
 * day-spa / beauty salon, which is NOT our target. Those languages therefore
 * lead with the retail-oriented compound ("venta de spas", "vente de spas")
 * and the hot-tub word carries the product meaning.
 */
const TERMS: Record<TermCategory, TermMap> = {
  spa: {
    en: ['spa dealer', 'spa retailer', 'hot tub showroom'],
    es: ['venta de spas', 'tienda de spas', 'distribuidor de spas'],
    ca: ['venda de spas', 'botiga de spas'],
    fr: ['vente de spas', 'magasin de spas', 'revendeur spa'],
    pt: ['venda de spas', 'loja de spas'],
    it: ['vendita spa idromassaggio', 'rivenditore spa'],
    de: ['Whirlpool Fachhandel', 'Whirlpool Studio'],
    nl: ['spa verkoop', 'spa dealer'],
    pl: ['sprzedaż spa jacuzzi', 'salon spa jacuzzi'],
    cs: ['prodej vířivek', 'vířivky prodejna'],
    sk: ['predaj vírivok'],
    hu: ['jakuzzi értékesítés', 'pezsgőfürdő forgalmazó'],
    ro: ['vanzare spa jacuzzi', 'magazin spa'],
    bg: ['продажба на спа джакузи'],
    el: ['πωλήσεις σπα υδρομασάζ'],
    sv: ['spabad försäljning', 'spabutik'],
    no: ['boblebad forhandler'],
    da: ['spabad forhandler'],
    fi: ['poreallas myynti'],
    et: ['mullivannide müük'],
    lv: ['spa baseinu tirdzniecība'],
    lt: ['sūkurinių vonių pardavimas'],
    tr: ['spa jakuzi satışı', 'jakuzi bayi'],
    ru: ['продажа спа бассейнов', 'джакузи салон'],
    uk: ['продаж спа басейнів'],
    ar: ['بيع جاكوزي', 'معرض جاكوزي'],
    he: ['מכירת ג׳קוזי'],
    hr: ['prodaja masažnih bazena'],
    sr: ['prodaja masažnih bazena'],
    sl: ['prodaja masažnih bazenov'],
    mk: ['продажба на џакузи'],
    sq: ['shitje jacuzzi'],
    is: ['heitir pottar sala'],
    ms: ['jualan spa jacuzzi'],
    id: ['jual spa jacuzzi'],
    th: ['ขายอ่างจากุซซี่'],
    vi: ['bán bồn tắm spa'],
    ja: ['ジャグジー 販売'],
    ko: ['스파 욕조 판매'],
    zh: ['spa水疗池 销售'],
  },
  hotTub: {
    en: ['hot tub dealer', 'hot tub store', 'jacuzzi dealer'],
    es: ['jacuzzi exterior venta', 'bañeras de hidromasaje'],
    ca: ['banyeres d hidromassatge'],
    fr: ['jacuzzi extérieur vente', 'spa de nage'],
    pt: ['jacuzzi exterior venda', 'banheiras de hidromassagem'],
    it: ['vasche idromassaggio esterne', 'minipiscine idromassaggio'],
    de: ['Whirlpool kaufen', 'Außenwhirlpool Händler'],
    nl: ['jacuzzi kopen', 'buitenspa'],
    pl: ['jacuzzi ogrodowe', 'wanny z hydromasażem'],
    cs: ['vířivky venkovní'],
    sk: ['vírivky vonkajšie'],
    hu: ['kültéri jakuzzi'],
    ro: ['jacuzzi exterior'],
    bg: ['външно джакузи'],
    el: ['υδρομασάζ εξωτερικού χώρου'],
    sv: ['utomhusspa jacuzzi'],
    no: ['utendørs boblebad'],
    da: ['udendørs spabad'],
    fi: ['ulkoporeallas'],
    et: ['välimullivann'],
    lv: ['āra spa vanna'],
    lt: ['lauko sūkurinė vonia'],
    tr: ['dış mekan jakuzi'],
    ru: ['уличное джакузи'],
    uk: ['вуличне джакузі'],
    ar: ['جاكوزي خارجي'],
    he: ['ג׳קוזי חיצוני'],
    hr: ['vanjski hidromasažni bazen'],
    sr: ['spoljni hidromasažni bazen'],
    sl: ['zunanji masažni bazen'],
    mk: ['надворешно џакузи'],
    sq: ['jacuzzi i jashtëm'],
    is: ['heitur pottur'],
    ms: ['tab mandi panas'],
    id: ['bak mandi air panas'],
    th: ['อ่างน้ำวนกลางแจ้ง'],
    vi: ['bồn tắm nước nóng ngoài trời'],
    ja: ['屋外ジャグジー 販売店'],
    ko: ['야외 스파 욕조'],
    zh: ['户外按摩浴缸 经销'],
  },
  swimSpa: {
    en: ['swim spa dealer', 'swim spa showroom'],
    es: ['piscina de nado contracorriente', 'swim spa venta'],
    fr: ['spa de nage vente'],
    pt: ['piscina de natacao contracorrente'],
    it: ['piscina a nuoto controcorrente'],
    de: ['Swim Spa Händler', 'Gegenstromanlage Pool'],
    nl: ['swimspa kopen'],
    pl: ['swim spa basen'],
    cs: ['protiproudý bazén swim spa'],
    hu: ['úszó spa medence'],
    ro: ['swim spa piscina'],
    sv: ['simspa'],
    no: ['svømmespa'],
    da: ['svømmespa'],
    fi: ['uima-allas spa'],
    tr: ['yüzme havuzu spa swim spa'],
    ru: ['плавательный спа бассейн'],
    ar: ['حوض سباحة سبا'],
    he: ['בריכת שחייה ספא'],
  },
  pool: {
    en: ['swimming pool company', 'pool supplier'],
    es: ['empresa de piscinas', 'tienda de piscinas'],
    ca: ['empresa de piscines'],
    fr: ['entreprise de piscines', 'magasin piscine'],
    pt: ['empresa de piscinas', 'loja de piscinas'],
    it: ['azienda piscine', 'negozio piscine'],
    de: ['Schwimmbadbau', 'Poolbau Firma'],
    nl: ['zwembadbedrijf', 'zwembadwinkel'],
    pl: ['firma basenowa', 'sklep basenowy'],
    cs: ['bazény firma'],
    sk: ['bazény firma'],
    hu: ['medence cég', 'medence szaküzlet'],
    ro: ['firma piscine', 'magazin piscine'],
    bg: ['фирма за басейни'],
    el: ['εταιρεία πισίνων'],
    sv: ['poolföretag', 'poolbutik'],
    no: ['basseng firma'],
    da: ['pool firma'],
    fi: ['uima-allas yritys'],
    et: ['basseinide firma'],
    lv: ['baseinu uzņēmums'],
    lt: ['baseinų įmonė'],
    tr: ['havuz firması', 'havuz market'],
    ru: ['бассейны компания'],
    uk: ['басейни компанія'],
    ar: ['شركة مسابح', 'محل مسابح'],
    he: ['חברת בריכות שחייה'],
    hr: ['tvrtka za bazene'],
    sr: ['firma za bazene'],
    sl: ['podjetje za bazene'],
    mk: ['фирма за базени'],
    sq: ['kompani pishinash'],
    is: ['sundlaugar fyrirtæki'],
    ms: ['syarikat kolam renang'],
    id: ['perusahaan kolam renang'],
    th: ['บริษัทสระว่ายน้ำ'],
    vi: ['công ty hồ bơi'],
    ja: ['プール 施工 会社'],
    ko: ['수영장 시공 업체'],
    zh: ['游泳池 公司'],
  },
  poolBuilder: {
    en: ['pool builder', 'pool construction company'],
    es: ['constructor de piscinas', 'construcción de piscinas'],
    ca: ['construcció de piscines'],
    fr: ['constructeur de piscines', 'pisciniste'],
    pt: ['construtor de piscinas', 'construção de piscinas'],
    it: ['costruttore piscine', 'costruzione piscine'],
    de: ['Schwimmbadbauer', 'Pool Bauunternehmen'],
    nl: ['zwembadbouwer'],
    pl: ['budowa basenów'],
    cs: ['stavba bazénů'],
    sk: ['stavba bazénov'],
    hu: ['medence építés'],
    ro: ['constructie piscine'],
    bg: ['строителство на басейни'],
    el: ['κατασκευή πισίνων'],
    sv: ['poolbyggare'],
    no: ['bassengbygger'],
    da: ['poolbygger'],
    fi: ['uima-altaan rakentaja'],
    tr: ['havuz yapımı', 'havuz inşaatı'],
    ru: ['строительство бассейнов'],
    uk: ['будівництво басейнів'],
    ar: ['بناء مسابح', 'مقاول مسابح'],
    he: ['בניית בריכות'],
    hr: ['izgradnja bazena'],
    sr: ['izgradnja bazena'],
    sl: ['gradnja bazenov'],
    ms: ['pembinaan kolam renang'],
    id: ['kontraktor kolam renang'],
    th: ['รับสร้างสระว่ายน้ำ'],
    vi: ['xây dựng hồ bơi'],
    ja: ['プール 建設'],
    ko: ['수영장 건설'],
    zh: ['泳池 建造'],
  },
  poolInstaller: {
    en: ['pool installer', 'pool maintenance company'],
    es: ['instalador de piscinas', 'mantenimiento de piscinas'],
    fr: ['installateur piscine', 'entretien piscine'],
    pt: ['instalador de piscinas', 'manutenção de piscinas'],
    it: ['installatore piscine', 'manutenzione piscine'],
    de: ['Poolmontage', 'Schwimmbadtechnik'],
    nl: ['zwembad installateur'],
    pl: ['montaż basenów'],
    cs: ['montáž bazénů'],
    hu: ['medence szerelés'],
    ro: ['instalare piscine'],
    el: ['συντήρηση πισίνας'],
    sv: ['poolinstallation'],
    tr: ['havuz bakım'],
    ru: ['обслуживание бассейнов'],
    ar: ['صيانة مسابح'],
    he: ['התקנת בריכות'],
  },
  wellness: {
    en: ['wellness company', 'wellness equipment supplier'],
    es: ['empresa de wellness', 'equipamiento wellness'],
    ca: ['empresa de wellness'],
    fr: ['entreprise bien-être', 'équipement bien-être'],
    pt: ['empresa de wellness', 'equipamento wellness'],
    it: ['azienda wellness', 'attrezzature benessere'],
    de: ['Wellness Fachhandel', 'Wellnessanlagen'],
    nl: ['wellness bedrijf'],
    pl: ['firma wellness'],
    cs: ['wellness firma'],
    sk: ['wellness firma'],
    hu: ['wellness cég'],
    ro: ['firma wellness'],
    bg: ['уелнес фирма'],
    el: ['εταιρεία ευεξίας'],
    sv: ['wellnessföretag'],
    no: ['velvære bedrift'],
    da: ['wellness virksomhed'],
    fi: ['hyvinvointi yritys'],
    tr: ['wellness firması'],
    ru: ['велнес оборудование'],
    uk: ['велнес обладнання'],
    ar: ['شركة عافية ومنتجعات'],
    he: ['חברת ספא ובריאות'],
    hr: ['wellness tvrtka'],
    sl: ['wellness podjetje'],
    ms: ['syarikat kesihatan wellness'],
    id: ['perusahaan wellness'],
    th: ['บริษัทเวลเนส'],
    vi: ['công ty chăm sóc sức khỏe'],
    ja: ['ウェルネス 設備'],
    ko: ['웰니스 업체'],
    zh: ['康养设备 公司'],
  },
  sauna: {
    en: ['sauna company', 'sauna supplier'],
    es: ['saunas venta', 'empresa de saunas'],
    ca: ['saunes venda'],
    fr: ['vente de saunas', 'fabricant sauna'],
    pt: ['venda de saunas'],
    it: ['vendita saune'],
    de: ['Saunabau', 'Sauna Fachhandel'],
    nl: ['sauna bedrijf'],
    pl: ['sauny sprzedaż'],
    cs: ['sauny prodej'],
    sk: ['sauny predaj'],
    hu: ['szauna értékesítés'],
    ro: ['saune vanzare'],
    bg: ['сауни продажба'],
    el: ['σάουνες πώληση'],
    sv: ['bastu företag'],
    no: ['badstue leverandør'],
    da: ['sauna forhandler'],
    fi: ['sauna yritys'],
    et: ['saunade müük'],
    lv: ['pirtis pārdošana'],
    lt: ['pirčių pardavimas'],
    tr: ['sauna firması'],
    ru: ['сауны продажа'],
    uk: ['сауни продаж'],
    ar: ['بيع ساونا'],
    he: ['סאונה מכירה'],
    hr: ['saune prodaja'],
    sr: ['saune prodaja'],
    sl: ['savne prodaja'],
    is: ['gufubað sala'],
    ja: ['サウナ 販売'],
    ko: ['사우나 시공'],
    zh: ['桑拿房 销售'],
  },
  hammam: {
    en: ['hammam steam room supplier', 'steam room company'],
    es: ['baño turco hammam instalación'],
    fr: ['hammam installation', 'fabricant hammam'],
    pt: ['banho turco hammam'],
    it: ['bagno turco hammam'],
    de: ['Dampfbad Hammam Bau'],
    nl: ['hammam stoomcabine'],
    pl: ['łaźnia parowa hammam'],
    el: ['χαμάμ ατμόλουτρο'],
    tr: ['hamam yapımı', 'buhar odası'],
    ru: ['хамам строительство'],
    ar: ['حمام بخار', 'حمام مغربي تركيب'],
    he: ['חמאם חדר אדים'],
  },
  outdoorLiving: {
    en: ['outdoor living company', 'garden living showroom'],
    es: ['empresa de exteriores y jardín', 'mobiliario de exterior'],
    ca: ['mobiliari d exterior'],
    fr: ['aménagement extérieur', 'mobilier de jardin haut de gamme'],
    pt: ['espaços exteriores mobiliario jardim'],
    it: ['arredo giardino esterni'],
    de: ['Outdoor Living Gartenausstattung'],
    nl: ['buitenleven tuinmeubelen'],
    pl: ['meble ogrodowe premium'],
    cs: ['zahradní nábytek premium'],
    hu: ['kerti bútor prémium'],
    ro: ['mobilier gradina premium'],
    el: ['έπιπλα κήπου εξωτερικού χώρου'],
    sv: ['utemiljö trädgårdsmöbler'],
    no: ['utemøbler hage'],
    da: ['havemøbler udeliv'],
    fi: ['pihakalusteet ulkotilat'],
    tr: ['bahçe mobilyası dış mekan'],
    ru: ['садовая мебель премиум'],
    ar: ['أثاث حدائق خارجي'],
    he: ['ריהוט גן חוץ'],
  },
  gardenPremium: {
    en: ['premium garden centre landscaping', 'luxury outdoor design'],
    es: ['centro de jardinería premium', 'paisajismo de lujo'],
    fr: ['paysagiste haut de gamme', 'jardinerie premium'],
    pt: ['paisagismo premium'],
    it: ['garden center premium paesaggistica'],
    de: ['Garten- und Landschaftsbau Premium'],
    nl: ['hoveniersbedrijf premium'],
    pl: ['architektura krajobrazu premium'],
    hu: ['kertépítés prémium'],
    ro: ['amenajari gradini premium'],
    el: ['αρχιτεκτονική τοπίου πολυτελείας'],
    sv: ['trädgårdsdesign premium'],
    tr: ['peyzaj mimarlığı lüks'],
    ru: ['ландшафтный дизайн премиум'],
    ar: ['تنسيق حدائق فاخر'],
    he: ['אדריכלות נוף יוקרה'],
  },
  hotelWellness: {
    en: ['hotel spa equipment supplier', 'hospitality wellness supplier'],
    es: ['proveedor de spa para hoteles', 'equipamiento spa hotelero'],
    fr: ['fournisseur spa hôtelier', 'équipement spa hôtel'],
    pt: ['fornecedor spa hoteleiro'],
    it: ['fornitore spa alberghiera'],
    de: ['Hotel Spa Ausstatter'],
    nl: ['hotel spa leverancier'],
    pl: ['wyposażenie spa hotelowego'],
    cs: ['vybavení hotelového wellness'],
    hu: ['hotel wellness beszállító'],
    ro: ['furnizor spa hotelier'],
    el: ['προμηθευτής spa ξενοδοχείων'],
    sv: ['hotell spa leverantör'],
    tr: ['otel spa ekipmanları'],
    ru: ['оборудование спа для отелей'],
    ar: ['تجهيزات سبا الفنادق'],
    he: ['ציוד ספא למלונות'],
  },
};

/**
 * Resolve the terms for a category in a set of languages.
 * Falls back to English so a market with no dictionary entry still searches.
 */
export function termsFor(category: TermCategory, languages: string[]): string[] {
  const map = TERMS[category];
  const out: string[] = [];
  for (const lang of languages) {
    for (const t of map[lang] ?? []) {
      if (!out.includes(t)) out.push(t);
    }
  }
  if (out.length === 0) out.push(...(map.en ?? []));
  return out;
}

/** True when we hold real local-language terms (not just the English fallback). */
export function hasLocalTerms(languages: string[]): boolean {
  return languages.some((l) => l !== 'en' && TERMS.spa[l] !== undefined);
}

export const TERM_CATEGORIES = Object.keys(TERMS) as TermCategory[];
export { TERMS };
